USE web_qua_luu_niem;

CREATE TABLE IF NOT EXISTS order_details(
id INT AUTO_INCREMENT PRIMARY KEY,
order_id INT NOT NULL,
product_id INT NOT NULL,
quantity INT NOT NULL,
price DECIMAL(10,2) NOT NULL,
FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;